version: '3.8'

services:
  db:
    build: ./database
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: flask_app
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "5001:5000"
    volumes:
      - .:/backend

  frontend:
    build: ./react-ui # Ensure this matches the frontend Dockerfile location
    container_name: react-ui
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - frontend:/frontend

volumes:
  pgdata:
  frontend:

networks:
  app_network:
    driver: bridge