version: '3.8'

services:
  db:
    build: ./database
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: flask_app
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/backend

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge